[DRAFT]Apply TestContainer
asyncer-io/r2dbc-mysql pull request #264
Opened 2024-03-16 02:37 UTC by jchrys

Motivation:
Enhance test reliability and environment consistency by integrating TestContainers

Modification:
Added TestContainers dependency and updated tests to run with containerized DBs.

Expanded test scope to include MySQL and MariaDB versions to cover conditional test cases.

Result:
Improved test suite stability and simplified setup for contributors. Resolves #76

2024-03-16 02:38 UTC, jchrys commented
I added the bug label because the absence of fine-grained database versioning fails to cover conditional test cases.

2024-03-16 02:41 UTC, jchrys commented
This PR is in very early phase of the change

2024-03-22 19:55 UTC, jchrys commented
TODO

- [ ] determine serverType(mariadb, mysql) and its version by connection context. (may utilize mysqlconnector-j and mariadb connector)

2024-03-31 07:28 UTC, jchrys commented
TODO
ADD Javadoc

2024-04-03 02:05 UTC, mirromutth requested changes

2024-04-03 02:05 UTC, mirromutth commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestContainerExtension.java
> +    @VisibleForTesting
Maybe remove it? Because `TestContainerExtension` is already in the `test` directory

```suggestion
```

2024-04-03 02:05 UTC, mirromutth commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestContainerExtension.java
> +                    ((MySQLContainer<?>) container).withConfigurationOverride("testcontainer/mysql-5.5");
Could you please explain why only MySQL 5.5 has `my.cnf`?

2024-04-03 02:05 UTC, mirromutth commented on .github/workflows/ci-mariadb-intergration-tests.yml
> +        mariadb-version: [ 10.0.38, 10.1.48, 10.2.15, 10.2.16, 10.3.7, 10.3.8, 10.5.1, 10.6.17, 10.11.7,
Is it necessary to use so many versions? Maybe it just needs to include every minor version. WDYT?

2024-04-03 02:05 UTC, mirromutth commented on .github/workflows/ci-integration-tests.yml
> +        mysql-version: [ 5.5.62, 5.6.34, 5.6.51, 5.7.10, 5.7.44, 8.0.11, 8.0.36, 8.1.0, 8.2.0,
Maybe it just needs to include every minor version and a few special versions.

2024-04-03 02:05 UTC, mirromutth commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/SessionStateIntegrationTest.java
> +        final String sql = "SELECT COUNT(*) " +
The query may be slower but not necessarily slower than the given timeout. If the test machine itself has excellent performance, it may cause the test case to fail. Why don't we continue to use `SLEEP`?

2024-04-03 02:05 UTC, mirromutth commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestContainerExtension.java
> +    @VisibleForTesting
```suggestion
```

2024-04-03 02:05 UTC, mirromutth commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ZstdCompressionIntegrationTest.java
Seems like missing an `@ExtendWith(TestContainerExtension.class)`.

The `TestContainerExtension` init container in `static` block, so we can just add it or remove all `@ExtendWith(TestContainerExtension.class)` in other classes.

2024-04-03 10:19 UTC, jchrys commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ZstdCompressionIntegrationTest.java
This test extends `IntegrationTestSupport.class` which has `@ExtendWith(TestContainerExtension.class)`.

2024-04-03 10:54 UTC, jchrys commented on .github/workflows/ci-integration-tests.yml
> +        mysql-version: [ 5.5.62, 5.6.34, 5.6.51, 5.7.10, 5.7.44, 8.0.11, 8.0.36, 8.1.0, 8.2.0,
cleaned it :D

2024-04-03 10:54 UTC, jchrys commented on .github/workflows/ci-mariadb-intergration-tests.yml
> +        mariadb-version: [ 10.0.38, 10.1.48, 10.2.15, 10.2.16, 10.3.7, 10.3.8, 10.5.1, 10.6.17, 10.11.7,
cleaned it :D

2024-04-03 11:11 UTC, jchrys commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestContainerExtension.java
> +                    ((MySQLContainer<?>) container).withConfigurationOverride("testcontainer/mysql-5.5");
mysql 5.5.x does not support `host_cache_size` but latest test container utilizes it :(
so we need to remove `host_cache_size` option when mysql version is 5.5.x and lower

2024-04-03 11:20 UTC, jchrys commented on r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/SessionStateIntegrationTest.java
> +        final String sql = "SELECT COUNT(*) " +
issue with Mariadb 10.2.15
```
Suppressed: io.r2dbc.spi.R2dbcBadGrammarException: [1064] [42000] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE SLEEP(1) > 1
```

2024-04-04 00:57 UTC, mirromutth approved these changes
LGTM

2024-04-04 01:28 UTC, merged