feat: support config AddressResolverGroup in r2dbc-mysql
asyncer-io/r2dbc-mysql pull request #279
Opened 2024-07-24 02:23 UTC by shoothzj

Motivation:
Currently,`AddressResolverGroup` can't be configured. The DnsResolver default start address listen to "0.0.0.0", which may have some security risks.
also see https://github.com/netty/netty/pull/11061

Modification:
Add `AddressResolverGroup` in Client's connect method

2024-07-24 02:39 UTC, CennyMo approved these changes

2024-07-24 22:58 UTC, shoothzj commented
@jchrys PTAL, thanks :)

2024-07-25 03:22 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +    private final AddressResolverGroup<?> resolver;
This field appears to be @Nullable. Additionally, there is no public method available to set this value. We need to support setting the resolver using Option methods.

You can refer to the following changes to add the new property and create test cases:
https://github.com/asyncer-io/r2dbc-mysql/pull/157

Please feel free to leave a comment if you need any further assistance.

2024-07-25 06:29 UTC, shoothzj commented
@jchrys Thank you for the reminder. I have fixed. However, I am still undecided on whether to name it resolver or resolverGroup. Do you have any preference?

2024-07-25 06:34 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +    AddressResolverGroup<?> getResolver() {
`@Nullable` seems missing

2024-07-25 06:38 UTC, jchrys commented
> @jchrys Thank you for the reminder. I have fixed. However, I am still undecided on whether to name it resolver or resolverGroup. Do you have any preference?

 I prefer "resolverGroup", since it refers to the underlying framework, keeping it as "resolverGroup" avoids any potential confusion.

2024-07-25 06:41 UTC, jchrys commented
> @jchrys Thank you for the reminder. I have fixed. However, I am still undecided on whether to name it resolver or resolverGroup. Do you have any preference?

Consider Reactor netty refers to it as `resolver`, I think sticking with resolver would be fine. :D

2024-07-25 07:14 UTC, jchrys requested changes
Just one last detail: I believe we have one final step to complete. Could you please check the following?
`MySqlConnectionConfiguration#equals`
`MySqlConnectionConfiguration#hashCode`
`MySqlConnectionConfiguration#toString`

`MySqlConnectionConfiguration#setup(ConnectionFactoryOptions)` and test of new option.

Thank you!

2024-07-25 07:14 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +    private final AddressResolverGroup<?> resolver;
```suggestion
    @Nullable
    private final AddressResolverGroup<?> resolver;
```

2024-07-25 07:14 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +        public Builder resolver(AddressResolverGroup<?> resolver) {
Could you please add the JavaDoc?

2024-07-25 08:38 UTC, shoothzj commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +        public Builder resolver(AddressResolverGroup<?> resolver) {
@jchrys Fixed

2024-07-25 08:38 UTC, shoothzj commented
@jchrys Thanks for your effort. PTAL again

2024-07-25 09:11 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/client/Client.java
> +        LoopResources loopResources, @Nullable AddressResolverGroup<?> resolverGroup) {
nit :D
```suggestion
        LoopResources loopResources, @Nullable AddressResolverGroup<?> resolver) {
```

2024-07-25 10:18 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/client/Client.java
> +            tcpClient = tcpClient.resolver(resolverGroup);
```suggestion
            tcpClient = tcpClient.resolver(resolver);
```

2024-07-25 10:19 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/client/Client.java
> +        if (resolverGroup != null) {
```suggestion
        if (resolver != null) {
```

2024-07-25 10:47 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProvider.java
> +        mapper.optional(RESOLVER).as(AddressResolverGroup.class);
```suggestion
        mapper.optional(RESOLVER).as(AddressResolverGroup.class)
            .to(builder::resolver);
```

2024-07-25 11:16 UTC, jchrys commented on r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
> +                (isHost ? "host='" + domain + "', port=" + port + ", ssl=" + ssl : "unixSocket='" + domain + "'") +
```suggestion
                (isHost ? "host='" + domain + "', port=" + port + ", ssl=" + ssl + 
                          ", tcpNoDelay=" + tcpNoDelay + ", tcpKeepAlive=" + tcpKeepAlive : 
                        "unixSocket='" + domain + "'") +
```

2024-07-25 11:42 UTC, jchrys approved these changes
@shoothzj 
Thanks a lot! :D

2024-07-25 11:45 UTC, merged