Simplify build jobs using a matrix
asyncer-io/r2dbc-mysql pull request #86
Opened 2023-04-09 06:15 UTC by saurabhyadav1985

Motivation: Reduce duplication in the GitHub Actions workflow unit-tests https://github.com/asyncer-io/r2dbc-mysql/issues/83

Modification: Refactored three jobs into one, now will build using strategy.matrix.version

Result: Jobs build for Java 8, 11 and 17 version.

2023-04-09 07:15 UTC, jchrys requested changes
Thank you very much for your PR! Just one small thing.

+ Could you please rebase and squash the changes to create a single commit?

Could you please add a line separator in the commit message, as shown below, to improve readability?
```
Motivation: 
Reduce ...

Modification: 
Refactored...

Result: 
Jobs...
```

2023-04-09 07:15 UTC, jchrys commented on .github/workflows/unit-tests.yml
> +  build:
Could you modify the code to clarify its purpose?
```suggestion
linux-build-java-${{ matrix.version }}:
```

2023-04-09 09:27 UTC, saurabhyadav1985 commented
Hey can you please delete my fork so I can fork again and raise PR as I am unable to squash into one commit

2023-04-09 13:34 UTC, jchrys commented
You don't need to delete your fork to achieve this; you can do it by yourself.

Try the following steps:

$ git checkout {yourbranch}
$ git rebase -i trunk
Squash all commits except the top one.
Create a commit message.
$ git push --force

2023-04-10 03:04 UTC, jchrys approved these changes

2023-04-11 20:03 UTC, merged

2023-04-11 20:04 UTC, jchrys commented
I squash merged to make it a single commit.
Thanks a lot!